# Generated by Django 5.1.4 on 2024-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_product_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('flat_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('apartment_size', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'flats2',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
