# Generated by Django 5.1.4 on 2024-12-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_flats_remove_products_category_delete_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
